import type { Metadata } from "next";
import { Montserrat, Montserrat_Subrayada } from "next/font/google";
import "./globals.css";
import { ReactNode } from "react";
import StoreProvider from "./4_shared/store/store-provider";
import cx from "clsx";
import { Prefetch } from "./2_widgets/prefetch";

const montserrat = Montserrat({
  variable: "--font-montserrat",
});

const montserratSubrayada = Montserrat_Subrayada({
  variable: "--font-montserrat-subrayada",
  weight: "400",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cx(montserrat.variable, montserratSubrayada.variable)}>
        <StoreProvider>
          <Prefetch>{children}</Prefetch>
        </StoreProvider>
      </body>
    </html>
  );
}
